version: '3.8'

services:
  wealth-manager-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: wealth-manager-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
    ports:
      - "1435:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume: